### ISSUE TITLE
node_type is incorrect

### ISSUE THREAD

**Issue by ytachioka** [TGV-CRN/TGV-CRN#3]
In model_GVCRN.py, L.263-264,
  node_type[:,0,0] = 1 # ego: [1 0] OK 
  node_type[:,0:,1] = 1 # non-ego: [0 1] OK

This assigns [1 1] for ego and [0 1] for non-ego. Is it OK?
I think these are intended according to the comment.
  node_type[:,0,0] = 1 # ego: [1 0] OK 
  node_type[:,1:,1] = 1 # non-ego: [0 1] OK

**Comment by ytachioka** [comment]
This did not degrade the performance

**Comment by TGV-CRN** [comment]
Thanks, it is correct. I will fix it.
